name: Deploy Cloudflare Worker

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Vite project
      - name: Build UI
        run: npm run build

      # Step 5: Install Wrangler globally
      - name: Install Wrangler
        run: npm install -g wrangler

      # Step 6: Publish to Cloudflare Workers
      - name: Publish Worker
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: npx wrangler publish
